apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
spec:
  selector:
    app: simple-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  clusterIP: 10.96.8.7
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127