apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env:
    - name: NGINX_SECRET_VARIABLE
      valueFrom:
        secretKeyRef:
          name: key3
          key: key3-secret
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
          