apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    app: webapp-color
spec:
  containers:
  - name: webapp-color
    image: webapp-image
    ports:
      - containerPort: 80
    envFrom:
      - configMapRef:
          name: app-config
        name: app-config
